### ISSUE TITLE
Bump to PHP 8.3

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-debugbar#21]

**Comment by bidi47** [comment]
blocked by
dotkernel/dot-twigrenderer

**Comment by arhimede** [comment]
waintig for this pull request 

https://github.com/mezzio/mezzio-twigrenderer/pull/33

**Comment by arhimede** [comment]
fixed in latest release 

https://github.com/mezzio/mezzio-twigrenderer/releases/tag/2.15.0

**Comment by arhimede** [comment]
must be alomost done

**Comment by arhimede** [comment]
fixed in release 1.1.5
